/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as HostCodeRouteImport } from './routes/host/$code'
import { Route as GameCodeRouteImport } from './routes/game/$code'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMyQuizzesIndexRouteImport } from './routes/_app/my-quizzes/index'
import { Route as AppMyQuizzesQuizIdRouteImport } from './routes/_app/my-quizzes/$quizId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const HostCodeRoute = HostCodeRouteImport.update({
  id: '/host/$code',
  path: '/host/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCodeRoute = GameCodeRouteImport.update({
  id: '/game/$code',
  path: '/game/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMyQuizzesIndexRoute = AppMyQuizzesIndexRouteImport.update({
  id: '/my-quizzes/',
  path: '/my-quizzes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMyQuizzesQuizIdRoute = AppMyQuizzesQuizIdRouteImport.update({
  id: '/my-quizzes/$quizId',
  path: '/my-quizzes/$quizId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AppProfileRoute
  '/game/$code': typeof GameCodeRoute
  '/host/$code': typeof HostCodeRoute
  '/': typeof AppIndexRoute
  '/my-quizzes/$quizId': typeof AppMyQuizzesQuizIdRoute
  '/my-quizzes': typeof AppMyQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AppProfileRoute
  '/game/$code': typeof GameCodeRoute
  '/host/$code': typeof HostCodeRoute
  '/': typeof AppIndexRoute
  '/my-quizzes/$quizId': typeof AppMyQuizzesQuizIdRoute
  '/my-quizzes': typeof AppMyQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/register': typeof RegisterRoute
  '/_app/profile': typeof AppProfileRoute
  '/game/$code': typeof GameCodeRoute
  '/host/$code': typeof HostCodeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/my-quizzes/$quizId': typeof AppMyQuizzesQuizIdRoute
  '/_app/my-quizzes/': typeof AppMyQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/play'
    | '/register'
    | '/profile'
    | '/game/$code'
    | '/host/$code'
    | '/'
    | '/my-quizzes/$quizId'
    | '/my-quizzes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/play'
    | '/register'
    | '/profile'
    | '/game/$code'
    | '/host/$code'
    | '/'
    | '/my-quizzes/$quizId'
    | '/my-quizzes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/play'
    | '/register'
    | '/_app/profile'
    | '/game/$code'
    | '/host/$code'
    | '/_app/'
    | '/_app/my-quizzes/$quizId'
    | '/_app/my-quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  RegisterRoute: typeof RegisterRoute
  GameCodeRoute: typeof GameCodeRoute
  HostCodeRoute: typeof HostCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/host/$code': {
      id: '/host/$code'
      path: '/host/$code'
      fullPath: '/host/$code'
      preLoaderRoute: typeof HostCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$code': {
      id: '/game/$code'
      path: '/game/$code'
      fullPath: '/game/$code'
      preLoaderRoute: typeof GameCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my-quizzes/': {
      id: '/_app/my-quizzes/'
      path: '/my-quizzes'
      fullPath: '/my-quizzes'
      preLoaderRoute: typeof AppMyQuizzesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my-quizzes/$quizId': {
      id: '/_app/my-quizzes/$quizId'
      path: '/my-quizzes/$quizId'
      fullPath: '/my-quizzes/$quizId'
      preLoaderRoute: typeof AppMyQuizzesQuizIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMyQuizzesQuizIdRoute: typeof AppMyQuizzesQuizIdRoute
  AppMyQuizzesIndexRoute: typeof AppMyQuizzesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppMyQuizzesQuizIdRoute: AppMyQuizzesQuizIdRoute,
  AppMyQuizzesIndexRoute: AppMyQuizzesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  RegisterRoute: RegisterRoute,
  GameCodeRoute: GameCodeRoute,
  HostCodeRoute: HostCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
